export enum PermissionTitle {
    USERS = 'USERS',
    DASHBOARD = 'DASHBOARD',
    VERIFICATION_OFFICERS = 'VERIFICATION_OFFICERS',
    EMERGENCY = 'EMERGENCY',
    ORGANIZATIONS = 'ORGANIZATIONS',
    ROLE_MANAGEMENT = 'ROLE_MANAGEMENT',
    CONFIGURATIONS = 'CONFIGURATIONS',
    VERIFICATION_PORTAL = 'VERIFICATION_PORTAL',

}
