name: Deploy Angular to Cloudways

on:
  push:
    branches:
      - main  # or any branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      REMOTE_PATH: ${{ secrets.REMOTE_PATH }}

    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: ⚙️ Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: 📦 Install dependencies
      run: npm install --legacy-peer-deps

    - name: 🛠️ Build Angular project
      run: npm run build --prod

    - name: 🔑 Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: 🧹 Clear remote directory
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "rm -rf $REMOTE_PATH/*"
    - name: 🚀 Deploy to Cloudways
      run: |
        scp -o StrictHostKeyChecking=no -r dist/* $SSH_USERNAME@$SSH_HOST:$REMOTE_PATH/
    - name: Move contents from folder and remove folder ref
      run: |
       ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "mv $REMOTE_PATH/aig-admin/* $REMOTE_PATH/ && rm -rf $REMOTE_PATH/aig-admin"
